// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkm58bMxCkAOAril4FoimrYVPhJBlogzM',
    appId: '1:260939547506:web:e70e17cdb4457862ff93eb',
    messagingSenderId: '260939547506',
    projectId: 'flutterandnode',
    authDomain: 'flutterandnode.firebaseapp.com',
    storageBucket: 'flutterandnode.appspot.com',
    measurementId: 'G-NN7JLTV3N4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXeMn87IalAoq1-Km2YF1h9kLMU_gwcqo',
    appId: '1:260939547506:android:78069cbb7f0146f3ff93eb',
    messagingSenderId: '260939547506',
    projectId: 'flutterandnode',
    storageBucket: 'flutterandnode.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzMF3z6x_v2Z1dwf23F4DODG6ncZHt65g',
    appId: '1:260939547506:ios:6c7692336be2bee0ff93eb',
    messagingSenderId: '260939547506',
    projectId: 'flutterandnode',
    storageBucket: 'flutterandnode.appspot.com',
    iosBundleId: 'com.example.commerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzMF3z6x_v2Z1dwf23F4DODG6ncZHt65g',
    appId: '1:260939547506:ios:d45e31f6716bfd07ff93eb',
    messagingSenderId: '260939547506',
    projectId: 'flutterandnode',
    storageBucket: 'flutterandnode.appspot.com',
    iosBundleId: 'com.example.commerce.RunnerTests',
  );
}
